// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDao2OwU-SwswFK-NNV-T6M-TBliWLytqk',
    appId: '1:1070016371716:web:06d908fa32078c7e62e951',
    messagingSenderId: '1070016371716',
    projectId: 'danilo-bank-geek',
    authDomain: 'danilo-bank-geek.firebaseapp.com',
    storageBucket: 'danilo-bank-geek.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCD-8DblpA6QpfikPshY4ejYswPLXkZok',
    appId: '1:1070016371716:android:85967f5a34231d0562e951',
    messagingSenderId: '1070016371716',
    projectId: 'danilo-bank-geek',
    storageBucket: 'danilo-bank-geek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO711o8ibqDW1pkmUYnSP_1hZnR8hUBfo',
    appId: '1:1070016371716:ios:73666e7438fc3b2c62e951',
    messagingSenderId: '1070016371716',
    projectId: 'danilo-bank-geek',
    storageBucket: 'danilo-bank-geek.appspot.com',
    iosClientId: '1070016371716-6nt2mjbp0ev91ig9fhrrhquf0r3gtkes.apps.googleusercontent.com',
    iosBundleId: 'awaken.com.bankGeek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO711o8ibqDW1pkmUYnSP_1hZnR8hUBfo',
    appId: '1:1070016371716:ios:73666e7438fc3b2c62e951',
    messagingSenderId: '1070016371716',
    projectId: 'danilo-bank-geek',
    storageBucket: 'danilo-bank-geek.appspot.com',
    iosClientId: '1070016371716-6nt2mjbp0ev91ig9fhrrhquf0r3gtkes.apps.googleusercontent.com',
    iosBundleId: 'awaken.com.bankGeek',
  );
}
